version: '3.8'

services:
  # Service Web (PHP + Apache)
  web:
    build: .
    container_name: wamp_web
    ports:
      - "8000:80"  # Port 8000 au lieu de 80 pour éviter les conflits
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - wamp_network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  # Service Base de données (MySQL) - CONTENEUR SÉPARÉ
  database:
    image: mysql:8.0
    container_name: wamp_mysql
    ports:
      - "3304:3306"  # Optionnel : pour accès externe
    environment:
      # Configuration pour connexion root sans mot de passe
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "wamp_db"
    volumes:
      # Persiste les données de la base de données Docker
      - mysql_data:/var/lib/mysql
      # Configuration MySQL personnalisée
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - wamp_network  # Communication avec conteneur web
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # PhpMyAdmin (optionnel, pour gérer la base de données)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wamp_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: ""
      PMA_ARBITRARY: 1
    depends_on:
      - database
    networks:
      - wamp_network

# Volumes persistants
volumes:
  mysql_data:
    driver: local

# Réseau pour la communication entre les services
networks:
  wamp_network:
    driver: bridge