name: 02-2 - Delivery - Trivy Scan

on:
  workflow_call

env:
  REGISTRY: ghcr.io
  USERNAME: ${{github.actor}}
  IMAGE_NAME: ${{github.repository}} #orga/repo

jobs:
  Trivy_Scan_CesiZen:
    runs-on: ubuntu-latest
    
    steps:
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Trivy CesiZen vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{env.REGISTRY}}/${{env.IMAGE_NAME_LOWER}}:canary
          format: 'table'
          exit-code: '1'
          output: 'cesizen-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy results CesiZen
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cesizen-trivy-results
          path: cesizen-trivy-results.txt
          retention-days: 1

      - name: Trivy Config Scan
        uses: aquasecurity/trivy-action@0.28.0
        if: always()
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          output: 'cesizen-config-scan.txt'

      - name: Upload Config Scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cesizen-config-scan
          path: cesizen-config-scan.txt
          retention-days: 1